CREATE TABLE ADMIN(
	USERNAME VARCHAR(10) UNIQUE
	,PASSWORD VARCHAR(50)
	,STATUS VARCHAR(10)
	);

CREATE TABLE COLLEGE_TYPE(
	COLLEGE_TYPE_ID VARCHAR(10) PRIMARY KEY
	,COLLEGE_TYPE VARCHAR(20)
	,DESCRIPTION VARCHAR(100)
	,IS_DELETED VARCHAR(1) DEFAULT '0'
	);
	
CREATE TABLE CITY(
	CITY_ID VARCHAR(10) PRIMARY KEY
	,CITY_NAME VARCHAR(20)
	,STATE VARCHAR(20)
	,PINCODE VARCHAR(10)
	,DESCRIPTION VARCHAR(100)
	,IS_DELETED VARCHAR(1) DEFAULT '0'
	);
	
CREATE TABLE ZONE(
	ZONE_ID VARCHAR(10) PRIMARY KEY
	,ZONE_NAME VARCHAR(20)
	,DESCRIPTION VARCHAR(100)
	,IS_DELETED VARCHAR(1) DEFAULT '0'
	);

CREATE TABLE COLLEGE (
	COLLEGE_ID VARCHAR(10) PRIMARY KEY
	,COLLEGE_NAME VARCHAR(50) NOT NULL
	,COLLEGE_TYPE VARCHAR(30)
	,ADDRESS1 VARCHAR(40)
	,ADDRESS2 VARCHAR(40)
	,CITY VARCHAR(20)
	,ZONE VARCHAR(20)
	,CONTACT_DETAILS VARCHAR(20)
	,EMAIL_ID VARCHAR(100)
	,CONTACT_PERSON VARCHAR(20)
	,COLLEGE_GRADE VARCHAR(10)
	,APPROVED_BY VARCHAR(20)
	,DESCRIPTION VARCHAR(100)
	,PASSWORD VARCHAR(50)
	,DATE_OF_JOINING DATE
	,STATUS VARCHAR(10)
	,IS_DELETED VARCHAR(1) DEFAULT '0'
	);
ALTER TABLE `college` CHANGE `DATE_OF_JOINING` `DATE_OF_JOINING` DATE NULL DEFAULT CURRENT_TIMESTAMP;	

CREATE TABLE COLLEGE_TPO(
	TPO_ID VARCHAR(10) PRIMARY KEY
	,COLLEGE_ID VARCHAR(10) REFERENCES COLLEGE(COLLEGE_ID)
	,TPO_NAME VARCHAR(20)
	,DEPARTMENT VARCHAR(10)
	,EMAIL VARCHAR(20)
	,PASSWORD VARCHAR(50)
	,STATUS VARCHAR(10)
	,REMARKS VARCHAR(20)
	,IS_DELETED VARCHAR(1) DEFAULT '0'
	);
	
	
CREATE TABLE STUDENT(
	STD_NAME VARCHAR(20)
	,STD_ID VARCHAR(10) PRIMARY KEY
	,COLLEGE_ID VARCHAR(10) REFERENCES COLLEGE(COLLEGE_ID)
	,REGISTRATION_NO VARCHAR(20)
	,SESSION_FROM VARCHAR(10)
	,SESSION_TO VARCHAR(10)
	,PASSWORD VARCHAR(50)
	,STATUS VARCHAR(10)
	,REMARKS VARCHAR(10)
	,IS_DELETED VARCHAR(1) DEFAULT '0'
	); 
	
CREATE TABLE STUDENT_PROFILE(
	STD_ID VARCHAR(10) REFERENCES STUDENT(STD_ID)
	,FATHERS_NAME VARCHAR(20)
	,MOTHERS_NAME VARCHAR(20)
	,DOB DATE
	,PRESENT_ADDRESS VARCHAR(40)
	,PERMANENT_ADDRESS VARCHAR(40)
	,HIGHEST_QUALIFICATION VARCHAR(10)
	,COURSE_INVOLVED VARCHAR(10)
	,AADHAR_NO VARCHAR(12)
	,PASSPORT_NO VARCHAR(10)
	,CURRENT_SEM VARCHAR(5)
	,HOBBIES VARCHAR(20)
	,DESCRIPTION VARCHAR(20)
	);
	

CREATE TABLE STUDENT_CREDENTIALS(
	CRED_ID VARCHAR(10) PRIMARY KEY
	,STD_ID VARCHAR(10) REFERENCES STUDENT(STD_ID)
	,CRED_NAME VARCHAR(20)
	,SCORE_OBTAINED VARCHAR(10)
	,SCORE_TYPE VARCHAR(10)
	,DOC_UPLOAD_STATUS VARCHAR(10)
	,VERIFIED VARCHAR(10)
	,VERIFICATION_DATE DATE
	,VERIFIED_BY VARCHAR(10) REFERENCES COLLEGE_TPO(TPO_ID)
	,IS_DELETED VARCHAR(1) DEFAULT '0'
	);
ALTER TABLE `student_credentials` CHANGE `VERIFIED` `VERIFIED` VARCHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0';
ALTER TABLE `student_credentials` CHANGE `DOC_UPLOAD_STATUS` `DOC_UPLOAD_STATUS` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'NO';

CREATE TABLE STUDENT_PREFERENCE(
	PREFERENCE_ID VARCHAR (10) PRIMARY KEY
	,STD_ID VARCHAR(10) REFERENCES STUDENT(STD_ID)
	,PREF_DOMAIN1 VARCHAR(20)
	,PREF_DOMAIN2 VARCHAR(20)
	,PREF_DOMAIN3 VARCHAR(20)
	,PREF_LOCATION1 VARCHAR(10)
	,PREF_LOCATION2 VARCHAR(10)
	,PREF_LOCATION3 VARCHAR(10)
	,PREF_TECH1 VARCHAR(10)
	,PREF_TECH2 VARCHAR(10)
	,PREF_TECH3 VARCHAR(10)
	);
	
	
CREATE TABLE INDUSTRY(
	INDUSTRY_ID VARCHAR(10) PRIMARY KEY
	,INDUSTRY_NAME VARCHAR(20)
	,ADDRESS VARCHAR(50)
	,PHONE_NO VARCHAR(20)
	,EMAIL_ID VARCHAR(100) UNIQUE
	,WEBSITE VARCHAR(40)
	,CONTACT_PERSON VARCHAR(20)
	,INDUSTRY_TYPE VARCHAR(20)
	,INDUSTRY_DOMAIN VARCHAR(30)
	,PASSWORD VARCHAR(50)
	,STATUS VARCHAR(10)
	,DESCRIPTION VARCHAR(100)
	,IS_DELETED VARCHAR(1) DEFAULT '0'
	);
	
	
	
CREATE OR REPLACE VIEW login_credentials as 
	SELECT 'ADMIN' as role, username, password(password) password, 'ADMINISTRATOR' name FROM `admin`
union
SELECT 'COLLEGE' as role, college_id, password(password) password, COLLEGE_NAME name FROM `college`
union
SELECT 'TPO' as role, tpo_id, password(password) password, TPO_NAME name FROM `college_tpo`
union
SELECT 'STUDENT' as role, std_id, password(password) password, STD_NAME name FROM `student`
union
SELECT 'INDUSTRY' as role, industry_id, password(password) password, INDUSTRY_NAME FROM `industry`;
	
DROP TABLE VACANCY;
CREATE TABLE VACANCY (
	VACANCY_ID VARCHAR(10) PRIMARY KEY
	, VACANCY_DATE DATE
	, INDUSTRY_ID VARCHAR(10)
	, VACANCY_FOR VARCHAR(10)
	, REQUIREMENT VARCHAR(20)
	, OPENING_DATE DATE
	, CLOSING_DATE DATE
	, VACANCY_HEAD VARCHAR(50)
	, VACANCY_BODY VARCHAR(100)
	, IS_DELETED VARCHAR(1) DEFAULT '0'
);

	
	
CREATE TABLE MESSAGES(
	MESSAGE_ID VARCHAR(10) PRIMARY KEY
	, MESSAGE_DATE TIMESTAMP
	, MESSAGE_FROM VARCHAR(10)
	, MESSAGE_TO VARCHAR(10)
	, MESSAGE_HEAD VARCHAR(50)
	, MESSAGE_BODY VARCHAR(200)
	, IS_READ VARCHAR(1) DEFAULT '0'
	, IS_DELETED VARCHAR(1) DEFAULT '0'
	);